### ISSUE TITLE
CommissioningClient.API is (temporarily?) not available

### ISSUE THREAD

**Issue by MartyMcFlyInTheSky** [google-home/sample-app-for-matter-android#112]
Last week when I tried to add a matter device it worked flawlessly (as far as I can tell). I got my lighbulb sample to work at least. Now I tried it again but adding a device fails with the following error message:

```
W/ConnectionStatusConfig: Dynamic lookup for intent failed for action: com.google.android.gms.home.service.START
W/GmsClient: unable to connect to service: com.google.android.gms.home.service.START on com.google.android.gms
E/GHSAFM-HomeViewModel: com.google.android.gms.common.api.ApiException: 17: API: CommissioningClient.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.1.0:3)
        at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@18.1.0:1)
        at com.google.android.gms.common.api.internal.zag.zad(com.google.android.gms:play-services-base@@18.1.0:1)
        at com.google.android.gms.common.api.internal.zabq.zaE(com.google.android.gms:play-services-base@@18.1.0:7)
        at com.google.android.gms.common.api.internal.zabq.zaD(com.google.android.gms:play-services-base@@18.1.0:2)
        at com.google.android.gms.common.api.internal.zabq.zar(com.google.android.gms:play-services-base@@18.1.0:24)
        at com.google.android.gms.common.api.internal.zabt.run(com.google.android.gms:play-services-base@@18.1.0:12)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
D/GHSAFM-HomeFragment: commissionDeviceStatus.observe: status [com.google.homesampleapp.TaskStatus$Failed@666f2ff]
```

Looks like some web API is temporarily unavailable. Can you confirm that? If so is there a workaround?

**Comment by tetedoie** [comment]
This is the same issue as #70. Are you trying on a different device ? The workaround is in the original ticket.

**Comment by pierredelisle** [comment]
Yeah, that issue is a bummer. We're still waiting for a proper fix.
