### ISSUE TITLE
Camera doesn't display preview frame in Google Play Service when use GPS to do matter provisioning.

### ISSUE THREAD

**Issue by M201370367** [google-home/sample-app-for-matter-android#134]
Has anyone met the issue: camera doesn't display preview frame in Google Play Service when use GPS to do matter provisioning?
GPS version: 23.17.60
phone : pixel 4a Android 13
![image](https://github.com/google-home/sample-app-for-matter-android/assets/6792012/e3a9afa4-bd7e-45cd-a1d1-97429c1599a1)
log:
java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases. Existing surfaces: [AttachedSurfaceInfo{surfaceConfig=SurfaceConfig{configType=PRIV, configSize=PREVIEW}, imageFormat=34, size=720x480, dynamicRange=DynamicRange@fed9bcc{format=FORMAT_SDR, bitDepth=8}, targetFrameRate=null}, AttachedSurfaceInfo{surfaceConfig=SurfaceConfig{configType=YUV, configSize=VGA}, imageFormat=35, size=640x480, dynamicRange=DynamicRange@fed9bcc{format=FORMAT_SDR, bitDepth=8}, targetFrameRate=null}] New configs: [m.ano@982e5e2, m.amr@d92ed73]
![image](https://github.com/google-home/sample-app-for-matter-android/assets/6792012/c8b3bcd8-3f54-416b-a224-65f5465b0f05)

**Comment by jonsmirl** [comment]
I have same issue on Samsung tablet, when my Pixel phone works fine.

**Comment by pierredelisle** [comment]
Could you provide complete phone logs as described in https://github.com/google-home/sample-app-for-matter-android/wiki/How-to-investigate-issues-with-the-sample-app-(GHSAFM). Thanks!

**Comment by jonsmirl** [comment]
[samsung.zip](https://github.com/google-home/sample-app-for-matter-android/files/11600948/samsung.zip)
Go to the end of it.
~~~
05-30 10:19:06.253 18425 18425 I SurfaceView@a1cd525: Changes: creating=false format=false size=false visible=false alpha=false hint=false mUseAlpha=false visible=false left=false top=true
05-30 10:19:06.253 18425 18425 I SurfaceView@a1cd525: 169661733 Cur surface: Surface(name=null)/@0xb05af20
05-30 10:19:06.254 18425 18425 I SurfaceView@a1cd525: applyTransactionOnVriDraw: vri = ViewRootImpl@732c2fd[SetupDeviceActivity] fRS = false t = 0xb4000075c70a3000 android.view.SurfaceView.performSurfaceTransaction:959 android.view.SurfaceView.updateSurface:1105 android.view.SurfaceView.lambda$new$0$android-view-SurfaceView:200 
05-30 10:19:06.254 18425 18489 W CaptureSession: Opening session with fail OPENING
05-30 10:19:06.254 18425 18489 W CaptureSession: java.lang.NullPointerException
05-30 10:19:06.254 18425 18489 W CaptureSession: 	at m.bgm.g(:com.google.android.gms.optional_home@231712065@23.17.12 (100400-0):0)
05-30 10:19:06.254 18425 18489 W CaptureSession: 	at m.xz.c(:com.google.android.gms.optional_home@231712065@23.17.12 (100400-0):25)
05-30 10:19:06.254 18425 18489 W CaptureSession: 	at m.xs.a(:com.google.android.gms.optional_home@231712065@23.17.12 (100400-0):0)
05-30 10:19:06.254 18425 18489 W CaptureSession: 	at m.aql.run(:com.google.android.gms.optional_home@231712065@23.17.12 (100400-0):5)
05-30 10:19:06.254 18425 18489 W CaptureSession: 	at m.aqh.run(:com.google.android.gms.optional_home@231712065@23.17.12 (100400-0):5)
05-30 10:19:06.254 18425 18489 W CaptureSession: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
05-30 10:19:06.254 18425 18489 W CaptureSession: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
05-30 10:19:06.254 18425 18489 W CaptureSession: 	at java.lang.Thread.run(Thread.java:1012)

~~~

That is logcat fom Google Home. This is something wrong in GPS. Camera won't work in either sample app or Google Home on my Samsung tablet. I think the Matter GPS code is asking for camera resolutions not supported by the camera.

**Comment by tcarmelveilleux** [comment]
@jonsmirl @M201370367 Could both of you tell us if a reboot of the device fixes the issue at least temporarily. That is, whether right after a fresh boot, the QR code camera works.

We are trying to determine if there may be an issue related to unreleased camera resources.

**Comment by jonsmirl** [comment]
No change on a reboot

**Comment by pierredelisle** [comment]
Issue has been filed at Google with the GPS team. Will report here as soon as I hear back.
