### ISSUE TITLE
Using Plus button to add device throws an error

### ISSUE THREAD

**Issue by matdev** [google-home/sample-app-for-matter-android#48]
I've built the "default" flavor of this Sample app, and now I'd like to add a real Matter device (e.g. ESP32) using the + button on the bottom right of Home page.
But when I click on the button, nothing happens, and I see the following error logs:

```
2022-11-28 17:56:49.445 14569-14869/com.google.homesampleapp.default W/ConnectionStatusConfig: Dynamic lookup for intent failed for action: com.google.android.gms.home.service.START
2022-11-28 17:56:49.448 14569-14869/com.google.homesampleapp.default W/GmsClient: unable to connect to service: com.google.android.gms.home.service.START on com.google.android.gms
2022-11-28 17:56:49.463 14569-14569/com.google.homesampleapp.default E/GHSAFM-HomeViewModel: com.google.android.gms.common.api.ApiException: 17: API: CommissioningClient.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.1.0:3)
        at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@18.1.0:1)
        at com.google.android.gms.common.api.internal.zag.zad(com.google.android.gms:play-services-base@@18.1.0:1)
        at com.google.android.gms.common.api.internal.zabq.zaE(com.google.android.gms:play-services-base@@18.1.0:7)
        at com.google.android.gms.common.api.internal.zabq.zaD(com.google.android.gms:play-services-base@@18.1.0:2)
        at com.google.android.gms.common.api.internal.zabq.zar(com.google.android.gms:play-services-base@@18.1.0:24)
        at com.google.android.gms.common.api.internal.zabt.run(com.google.android.gms:play-services-base@@18.1.0:12)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)

```

This error occurs both on my Pixel 4a on Android 13 and my Android 12 smartphone.

Can you please help ?

**Comment by pierredelisle** [comment]
The following error:
 ```
2022-11-28 17:56:49.463 14569-14569/com.google.homesampleapp.default E/GHSAFM-HomeViewModel: com.google.android.gms.common.api.ApiException: 17: API: CommissioningClient.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
```
means that your phone does not have the required "home" module from Google Play Services.
See https://developers.home.google.com/matter/verify-services for details on how to fix this.

**Comment by matdev** [comment]
After updating Google Services and uninstalling then reinstalling Google Home app, I can now use the + button.
Thank you Pierre for the help !

**Comment by matdev** [comment]
The sample app requires Google Services services version 22.30 or higher. Do you know if Google plans to ship the Matter services natively in futures versions of Android, and if so, in which version please ?

**Comment by pierredelisle** [comment]
I do not know of any other plan besides the current one which is the "Home" API as part of Google Play Services.
