### ISSUE TITLE
Something went wrong with google sample app (GHSAFM) 

### ISSUE THREAD

**Issue by kaiyu723** [google-home/sample-app-for-matter-android#64]
My device is silab evb for matter over wifi, but GHSAFM always get the following error.
Please help to check.

```
01-06 19:18:35.389  2259  2259 I MatterCommissioner: Sent CommissioningComplete. [CONTEXT service_id=336 ]
01-06 19:18:35.389  2259  5073 D EM      : Flushed pending ack for MessageCounter:252160983 on exchange 64964i
01-06 19:18:35.389  2259  2259 I MatterCommissioner: Commissioning completed successfully. [CONTEXT service_id=336 ]
01-06 19:18:35.389  2259  2259 I SetupDeviceViewModel: **Commissioning completed successfully**. [CONTEXT service_id=336 ]
01-06 19:18:35.389  2259  2259 I BleScanner: Disconnecting and closing Bluetooth GATT connection. [CONTEXT service_id=336 ]
01-06 19:18:35.397  2259  2259 I SetupDeviceChimeraActiv: Commissioning service provided; opening a commissioning window. [CONTEXT service_id=336 ]
01-06 19:18:36.183  2259  2259 I SetupDeviceViewModel: Opened commissioning window at fe80::8ada:1aff:fee4:bc14%38[5540] [CONTEXT service_id=336 ]
01-06 19:18:36.189  2259  2259 I CommissioningServiceBin: Sending commissioning request to bound service. [CONTEXT service_id=336 ]
01-06 19:19:26.673  2259  2259 W CommissioningServiceBin: Disconnected from service ComponentInfo{com.google.homesampleapp.default/com.google.homesampleapp.commissioning.AppCommissioningService} [CONTEXT service_id=336 ]
01-06 19:19:27.802  2259  2259 I CommissioningServiceBin: Connected to service ComponentInfo{com.google.homesampleapp.default/com.google.homesampleapp.commissioning.AppCommissioningService}. [CONTEXT service_id=336 ]
**01-06 19:20:36.193  2259  2259 W CommissioningServiceBin: Gave up waiting for commissioning response after 120000ms [CONTEXT service_id=336 ]
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: Showing error status. [CONTEXT service_id=336 ]
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: m.fjj: Timed out waiting for commissioner to respond (ComponentInfo{com.google.homesampleapp.default/com.google.homesampleapp.commissioning.AppCommissioningService}).**
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at m.fpa.a(:com.google.android.gms.optional_home@224915065@22.49.15 (100400-0):12)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at m.bnj.b(:com.google.android.gms.optional_home@224915065@22.49.15 (100400-0):2)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at m.bnj.f(:com.google.android.gms.optional_home@224915065@22.49.15 (100400-0):4)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at m.bno.j(:com.google.android.gms.optional_home@224915065@22.49.15 (100400-0):3)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at m.bng.run(:com.google.android.gms.optional_home@224915065@22.49.15 (100400-0):0)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at android.os.Handler.handleCallback(Handler.java:883)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at android.os.Looper.loop(Looper.java:238)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at android.app.ActivityThread.main(ActivityThread.java:7823)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at java.lang.reflect.Method.invoke(Native Method)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
01-06 19:20:36.195  2259  2259 E SetupDeviceChimeraActiv: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1017)
```

[logcat4.txt](https://github.com/google-home/sample-app-for-matter-android/files/10359816/logcat4.txt)

**Comment by kaiyu723** [comment]
Is there any expert to help solve the problem?

**Comment by kaiyu723** [comment]
The same device works well by apple Home.

**Comment by pierredelisle** [comment]
Looks like the sample app did not get control back after the commissioning on the Android local fabric completed. Would need the full logs of the phone to investigate.

Also, please see https://github.com/google-home/sample-app-for-matter-android/wiki/How-to-investigate-issues-with-the-sample-app-(GHSAFM).

**Comment by pierredelisle** [comment]
Closing this for now as complete logs were not provided to investigate further.

**Comment by ThanhChen** [comment]
I've encounter this issue
Please take a look at my log @pierredelisle 

[commissioning_02072023_1.txt](https://github.com/google-home/sample-app-for-matter-android/files/10673560/commissioning_02072023_1.txt)

**Comment by pierredelisle** [comment]
Looked at the logs.
It appears that commissioning was first attempted and failed:
```
16:11:35.022 15978 15978 I MatterCommissioner: Starting commissioning flow for sessionId: 657435589949857581 and device identifier: Discriminator L[0xF09]. [CONTEXT service_id=336 ]
...
16:13:55.281 15978 15978 E MatterCommissioner: Giving up CASE connection after 3 attempts. [CONTEXT service_id=336 ]
```
 
Then a second time, and failed again.
```
16:14:12.554 15978 15978 I MatterCommissioner: Starting commissioning flow for sessionId: 657435589949857581 and device identifier: Discriminator L[0xF09]. [CONTEXT service_id=336 ]
...
16:15:01.950 15978 15978 I MatterCommissioner: Establishing a CASE connection. (3 of 3) [CONTEXT service_id=336 ]
```

Then on the third attempt, looks like it succeeded and the sample app was triggered to do its own commissioning:
```
16:15:35.986 15978 15978 I MatterCommissioner: Starting commissioning flow for sessionId: 657435589949857581 and device identifier: Discriminator L[0xF09]. [CONTEXT service_id=336 ]
...
16:15:44.553 15978 15978 I MatterCommissioner: Commissioning completed successfully. [CONTEXT service_id=336 ]
...
16:15:45.119 26709 26709 D GHSAFM-AppCommissioningService$onCommissioningRequested: Commissioning: App fabric -> ChipClient.establishPaseConnection(): deviceId [3]
```

Unfortunately, there's nothing in the logs after that related to matter or the sample app to provide some insight as to what went wrong.

All I can suggest is to clear the app state (see https://github.com/google-home/sample-app-for-matter-android/wiki/How-to-investigate-issues-with-the-sample-app-(GHSAFM)#clean-state), and try to test with a different device?

**Comment by ThanhChen** [comment]
Yes, I try to test with 

Samsung Galaxy A52
Android 12
Google Play version:  com.google.android.gms.optional_home [230313065] [23.03.13 (100400-0)] [Download:0000013e/dl-Home.optional_230313100400.apk] [download:/Home.optional/230313100400:Home.optional:230313100400
GHSAFM version: 1.3.0-default

And result is same:
[commissioning_samphone_02082023_1.txt](https://github.com/google-home/sample-app-for-matter-android/files/10682361/commissioning_samphone_02082023_1.txt)

**Comment by pierredelisle** [comment]
Actually, now the logs include the source of the issue:

```
02-08 13:06:11.911 28354 29632 D GHSAFM-BaseCompletionListener: onCommissioningStatusUpdate nodeId [1]  stage [SendOpCertSigningRequest]  errorCode [50]
02-08 13:06:11.912 28354 29632 D CTL     : Error on commissioning step 'SendOpCertSigningRequest': '../../src/app/CommandSender.cpp:248: CHIP Error 0x00000032: Timeout'
02-08 13:06:11.912 28354 29632 E CTL     : Failed to perform commissioning step 9
02-08 13:06:11.912 28354 29632 D CTL     : Going from commissioning step 'SendOpCertSigningRequest' with lastErr = '../../src/app/CommandSender.cpp:248: CHIP Error 0x00000032: Timeout' -> 'Cleanup'
02-08 13:06:11.912 28354 29632 D CTL     : Performing next commissioning step 'Cleanup' with completion status = '../../src/app/CommandSender.cpp:248: CHIP Error 0x00000032: Timeout'
02-08 13:06:11.912 28354 29632 D CTL     : Expiring failsafe on proxy 0xb400006d6b4d1158
02-08 13:06:11.912 28354 29632 D DMG     : ICR moving to [AddingComm]
02-08 13:06:11.912 28354 29632 D DMG     : ICR moving to [AddedComma]
02-08 13:06:11.912 28354 29632 D EM      : <<< [E:5451i M:596565] (S) Msg TX to 0:FFFFFFFB00000000 [0000] --- Type 0001:08 (IM:InvokeCommandRequest)
02-08 13:06:11.913 28354 29632 D IN      : (S) Sending msg 596565 on secure session with LSID: 44454
02-08 13:06:11.914 28354 29632 D DMG     : ICR moving to [CommandSen]
02-08 13:06:11.914 28354 29632 D DMG     : ICR moving to [AwaitingDe]
```

**Comment by ThanhChen** [comment]
I have no idea what should be wrong from GHSAFM. But when i've tried to use an already-reserved nodeID to commission device. Scenerio:
1.  Developer  commissions device using node ID 1
2. Developer factory resets the device
3.  Developer tries to commission the same device using node ID=1.

It's worked. Weird!

**Comment by ThanhChen** [comment]
> Failed to perform commissioning step 9

@pierredelisle Thanks for your investigating. Could I get a guide to resolve this?
