### ISSUE TITLE
Is there a sample app for Matter Thread ?

### ISSUE THREAD

**Issue by matdev** [google-home/sample-app-for-matter-android#67]
I'm looking for an app equivalent to GHSAFM allowing commissioningof  Matter Thread devices (possibly via a border router such as Google Nest).

Any suggestion please ?

**Comment by pierredelisle** [comment]
We don't have an equivalent of GHSAFM for showcasing the Thread Network SDK for Android (https://developers.home.google.com/thread).

However, please note that GHSAFM can be used to commission Matter-enabled Thread devices.

**Comment by matdev** [comment]
Do you mean it's possible to control a Matter-enabled Thread device from a custom android app without a border router or Google Nest ?
How could this be possible since smartphones don't support Thread natively ?

**Comment by pierredelisle** [comment]
You definitely need a thread border router for this to work.
For example, with a Nest Hub and a Thread Matter device, I can commission the thread matter device and control it with the sample app.

**Comment by matdev** [comment]
I have a Matter enabled Thread device from Telink and a Google Nest.
I'm trying to commission the Matter device with the sample app, but the app says 'Can't find device".

Any idea why please ?

Here are the logs captured after scanning the device's QR code.
[logs.txt](https://github.com/google-home/sample-app-for-matter-android/files/10448767/logs.txt)

**Comment by pierredelisle** [comment]
From the logs, I can see that commissioning was initiated by the app:
```
01-18 17:51:46.119 20317 20317 D GHSAFM-HomeFragment: CommissionDevice: Launch GPS activity to commission device
```
However, the app never gets control back from the commissioning activity that was launched.
We can see why here:
```
01-18 17:52:55.884 17388 17388 I MatterCommissioner: No matching devices discovered. [CONTEXT service_id=336 ]
01-18 17:52:55.887 17388 17439 I BleScanner: Stopping BLE scanning [CONTEXT service_id=336 ]
01-18 17:52:55.887 17388 17437 I MdnsScanner: Stopping mDNS discovery. [CONTEXT service_id=336 ]
01-18 17:52:55.887 17388 17439 D BluetoothAdapter: isLeEnabled(): ON
01-18 17:52:55.888 17388 19705 I BleConnectorImpl: Bluetooth scan was cancelled [CONTEXT service_id=336 ]
01-18 17:52:55.890  2632  3398 D ActivityAttributionService: notifyActivityAttributionInfo UID=1002 packageName=com.android.bluetooth deviceAddress=no_active_device_address
01-18 17:52:55.890  2632  3398 I bt_btif : packages/modules/Bluetooth/system/btif/src/bluetooth.cc:471 get_profile_interface: get_profile_interface: id = activity_attribution
01-18 17:52:55.890  2632  2952 I bt_stack: [INFO:le_scanning_manager.cc(172)] ScanFilterParamSetup in shim layer
01-18 17:52:55.893  2632  3398 I bt_stack: [INFO:le_scanning_manager.cc(146)] Unregister in shim layer, scanner_id:9
01-18 17:52:55.894  2632  2952 I bt_stack: [INFO:le_scanning_manager.cc(152)] Scan in shim layer stopped
01-18 17:52:55.894  2632  2952 I bt_stack: [INFO:le_scanning_manager.cc(248)] SetScanParameters in shim layer
01-18 17:52:55.894  2632  2952 I bt_stack: [INFO:le_scanning_manager.cc(152)] Scan in shim layer started
01-18 17:52:55.896  2632  2963 I bluetooth: packages/modules/Bluetooth/system/gd/hci/le_scanning_manager.cc:653 stop_scan: Scanning already stopped, return!
01-18 17:52:55.896  2632  2963 I bluetooth: packages/modules/Bluetooth/system/gd/hci/le_scanning_manager.cc:653 stop_scan: Scanning already stopped, return!
01-18 17:52:55.899 17388 17388 E SetupDeviceViewModel: Commissioning failed with state Failed to discover commissionable device. [CONTEXT service_id=336 ]
```

Maybe there's an issue with the device advertising itself properly?

If you build the sample app from master, there is a new Developer Utility to discover commissionable devices. It would be good to  see if the device shows up.
I'll try to release 1.3.0 by end of week if you just want to use the new APK that will then be available.

**Comment by pierredelisle** [comment]
V1.3.0 has just been released. 
See https://github.com/google-home/sample-app-for-matter-android/releases/tag/v1.3.0.

Please use that APK and verify that the device does show up in the discovered commissionable Matter devices.
Settings > Developer utilities > Commisionable devices

**Comment by matdev** [comment]
Thanks Pierre. After updating my repo, I'm able see my Telink device in the new "Commissionable Devices" screen. Its MAC address is CE:9F:DF:E3:13:76

However, installing this device in the sample app still fails. Here are the logs from the app:
[logs.txt](https://github.com/google-home/sample-app-for-matter-android/files/10481784/logs.txt)

and the log from Telink devKit:
[logs from Telink Thread devKit.txt](https://github.com/google-home/sample-app-for-matter-android/files/10481801/logs.from.Telink.Thread.devKit.txt)

Hope this helps

**Comment by pierredelisle** [comment]
Looking at the phone logs:
```
01-23 17:35:04.687 20605 20605 D GHSAFM-HomeFragment: CommissionDevice: Launch GPS activity to commission device
...
01-23 17:35:32.864 27124 27124 I MatterCommissioner: Connected to Thread network. [CONTEXT service_id=336 ]
...
01-23 17:35:32.876 27124 27124 I MatterCommissioner: Establishing a CASE connection. (1 of 3) [CONTEXT service_id=336 ]
...
01-23 17:35:47.956 27124 27124 W MatterCommissioner: Failed to establish CASE connection; retrying (1 of 3) in 1,000 ms. [CONTEXT service_id=336 ]
01-23 17:35:47.956 27124 27124 W MatterCommissioner: m.eiu: Failed to resolve pointer for device A23F2BB89ECBF0F6
01-23 17:35:47.956 27124 27124 W MatterCommissioner: 	at m.efs.onConnectionFailure(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):3)
01-23 17:35:47.956 27124 27124 W MatterCommissioner: Caused by: chip.devicecontroller.ChipDeviceControllerException: third_party/connectedhomeip/next/src/lib/address_resolve/AddressResolve_DefaultImpl.cpp:174: CHIP Error 0x00000032: Timeout
...
01-23 17:35:48.961 27124 27124 I MatterCommissioner: Establishing a CASE connection. (2 of 3) [CONTEXT service_id=336 ]
...
01-23 17:35:50.157 27124 27124 W MatterCommissioner: Failed to establish CASE connection; retrying (2 of 3) in 2,000 ms. [CONTEXT service_id=336 ]
01-23 17:35:50.157 27124 27124 W MatterCommissioner: m.eiu: Failed to resolve pointer for device A23F2BB89ECBF0F6
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.efs.onConnectionFailure(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):3)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at chip.platform.ChipMdnsCallbackImpl.handleServiceResolve(Native Method)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.evv.j(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):7)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.evv.b(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):6)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.ngq.f(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):4)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.nvx.bq(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):0)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.nlp.f(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):4)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.ngq.f(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):8)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.nno.run(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):8)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.dpc.c(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):6)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at m.dpc.run(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):7)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at aajd.run(:com.google.android.gms@225014037@22.50.14 (150400-499278674):0)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: 	at java.lang.Thread.run(Thread.java:923)
01-23 17:35:50.157 27124 27124 W MatterCommissioner: Caused by: chip.devicecontroller.ChipDeviceControllerException: third_party/connectedhomeip/next/src/inet/UDPEndPointImplSockets.cpp:409: OS Error 0x02000065: Network is unreachable
...
01-23 17:35:53.434 27124 27124 E MatterCommissioner: Giving up CASE connection after 3 attempts. [CONTEXT service_id=336 ]
01-23 17:35:53.434 27124 27124 E MatterCommissioner: m.eiu: Failed to resolve pointer for device A23F2BB89ECBF0F6
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.efs.onConnectionFailure(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):3)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at chip.platform.ChipMdnsCallbackImpl.handleServiceResolve(Native Method)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.evv.j(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):7)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.evv.b(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):6)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.ngq.f(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):4)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.nvx.bq(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):0)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.nlp.f(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):4)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.ngq.f(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):8)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.nno.run(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):8)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.dpc.c(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):6)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at m.dpc.run(:com.google.android.gms.optional_home@225014065@22.50.14 (100400-0):7)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at aajd.run(:com.google.android.gms@225014037@22.50.14 (150400-499278674):0)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	at java.lang.Thread.run(Thread.java:923)
01-23 17:35:53.434 27124 27124 E MatterCommissioner: Caused by: chip.devicecontroller.ChipDeviceControllerException: third_party/connectedhomeip/next/src/inet/UDPEndPointImplSockets.cpp:409: OS Error 0x02000065: Network is unreachable
01-23 17:35:53.434 27124 27124 E MatterCommissioner: 	... 14 more
01-23 17:35:53.435  1108  1558 E surfaceflinger: [frame_perf] perfboost open boost file failed
01-23 17:35:53.437 27124 27124 I MatterCommissioner: Disarming failsafe. [CONTEXT service_id=336 ]
```

So the MatterCommissioner in GPS fails to setup a CASE connection with the device.

What would help is if your device logs had a timestamp to be able to sync the two logs and try to understand why the CASE session cannot be established with the device. 

But TBH, at this point I would suggest filing an issue with those logs to the Telink team, they'd know best what's happening on the device side.
