### ISSUE TITLE
Crash when opening the sample app  (BUG)

### ISSUE THREAD

**Issue by BouthainaTouati** [google-home/sample-app-for-matter-android#97]
/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.homesampleapp.default, PID: 9256
    **java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~jx_Fe-eqYxS-tONr3Cy6XQ==/com.google.homesampleapp.default-wKyd-x-gqtdpLGME0SbYeQ==/base.apk!/lib/arm64-v8a/libCHIPController.so" has bad ELF magic: 76657273**
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1661)
        at chip.devicecontroller.ChipDeviceController.<clinit>(ChipDeviceController.java:747)
        at chip.devicecontroller.ChipDeviceController.loadJni(ChipDeviceController.java:44)
        at com.google.homesampleapp.chip.ChipClient$chipDeviceController$2.invoke(ChipClient.kt:52)
        at com.google.homesampleapp.chip.ChipClient$chipDeviceController$2.invoke(ChipClient.kt:51)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.google.homesampleapp.chip.ChipClient.getChipDeviceController(ChipClient.kt:51)
        at com.google.homesampleapp.screens.home.HomeFragment.setDeviceAttestationDelegate(HomeFragment.kt:432)
        at com.google.homesampleapp.screens.home.HomeFragment.onCreate(HomeFragment.kt:152)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1967)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:169)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1729)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
        at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
        at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:710)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
E/AndroidRuntime:     at com.google.homesampleapp.MainActivity.onCreate(MainActivity.kt:41)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by pierredelisle** [comment]
Hmm, do you build from source or used the APK of a specific release. Also, on which architecture (phone processor) are you running the app?

**Comment by BouthainaTouati** [comment]
I forked the project from the repository and am running it with "google pixel 3a"

**Comment by pierredelisle** [comment]
> I forked the project from the repository and am running it with "google pixel 3a"
@BouthainaTouati I really need complete details to be able to reproduce. Please start from scratch and put all details in the issue. Only then can we help you.

As an alternative, we just released v1.4.1 (see https://github.com/google-home/sample-app-for-matter-android/releases/tag/v1.4.1). Why don't you download the default APK and tell us how it goes.

**Comment by pierredelisle** [comment]
We've had another report of the same exception and we've finally figured out the cause.
If you clone the repo, make sure to follow the instructions here:
https://github.com/google-home/sample-app-for-matter-android#clone-the-repository

More specifically:
"... and require the use of Git Large File Storage (LFS)."

Your APK size was probably quite small, which means that the Matter SDK libraries (which require LFS) were not included.
